# Generated by Django 4.2 on 2026-02-15 17:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='events/thumbnails/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rating',
            field=models.PositiveIntegerField(default=0, help_text='Оценка мероприятия от 0 до 25', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', help_text='Опубликованные мероприятия видны всем, черновики — только админам', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=6, help_text='Географическая широта в десятичном формате', max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.DecimalField(decimal_places=6, help_text='Географическая широта/долгота в десятичном формате', max_digits=9, verbose_name='Долгота'),
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура (°C)')),
                ('humidity', models.FloatField(verbose_name='Влажность (%)')),
                ('pressure', models.FloatField(verbose_name='Давление (мм рт. ст.)')),
                ('wind_direction', models.CharField(max_length=50, verbose_name='Направление ветра')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра (м/с)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='events.event')),
            ],
        ),
    ]
